### ISSUE TITLE
어케 삭제해요

### ISSUE THREAD

**Issue by dahyyye** [umc7thseminar/seminar_7thumc#20]
## 🛠️ Issue Description
[//]: # (해당 이슈에 대한 설명을 작성해주세요.)

## 💭 How to test
[//]: # (무엇을 위한 테스트인지, 어떻게 테스트를 진행할 것인지 작성해주세요.)

### 📝 check-lists
[//]: # (업무 체크리스트를 작성해주세요.)
- [ ] Task1

**Comment by bianbbc87** [comment]
헉 이제야 봤는데..ㅠㅠ 이슈는 삭제가 불가능하고 Close만 가능합니다 !
때문에 이슈를 잘못 올린 경우 Edit을 통해 자유롭게 수정할 수 있습니다 😄

<img width="897" alt="image" src="https://github.com/user-attachments/assets/7dcab227-dce2-4b41-bbaa-5e46cfd00022">

위 버튼을 통해 Close 할 수 있고, Close as not planned로 계획에 영향이 안 가도록 close 할 수 있습니다 !

**Comment by bianbbc87** [comment]
이 메시지랑 같이 close 하겠습니다

**Comment by bianbbc87** [comment]
Reopen이나 completed로 변경도 가능합니다 !

<img width="897" alt="image" src="https://github.com/user-attachments/assets/6fb5825a-de25-406e-8f55-bc55d7cbe482">
